### PR TITLE
nsfw window react and related topic override

### PR DESCRIPTION
**Pull request by TreeWizard96**
Overrides two existing labels, partially to show that it can be done, but also to address #59.
This currently piggybacks off of the existing window react setup starting at line 187 of the script-windowreacts.rpy file in the main mod, basically reacting whenever the player has a page open with a title containing things like "monika rule34". This addition adds Love level affection reactions. 
It also edits the monika_nsfw label event so that if you have sexted before, she will mention it.

### CODE REVIEW

**Comment by TreeWizard96** [comment]
Marked this as a WIP as I'll be taking suggestions for new window reacts and/or topics.

**Comment by TreeWizard96** [comment]
Alright I've done testing and some final tweaks. Should be ready to go.

**Comment by NickWildish** [comment]
Just noticed we should probably be pushing this into dev. Unless you were intending to push to main?

**Comment by TreeWizard96** [comment]
> Just noticed we should probably be pushing this into dev. Unless you were intending to push to main?

Yeah, mistake on my part.

**Comment by NickWildish** [comment]
Cool, looks good!

**Pull request merged**
