### PR TITLE
Adds a way for Monika to pick random underwear each day

### PR DESCRIPTION
**Pull request by ML-Gaming**
Adds a range of subroutines in the main to be called in topics which then have her change into the corresponding underwear. Can be expanded easily if more underwear sprites get made and added.

### CODE REVIEW

**Comment by NickWildish** [comment]
Would it be alright for me to apply this change to the dev branch rather than the main branch? I was in the process of working on a way for Monika to change underwear already in 'dev' so I would like your work to overwrite it.

**Comment by NickWildish** [comment]
Also, feel free to DM me on the Discord server so I can assign you a contributor role. I'm afraid I can't find this username you've used for GitHub on the server.

**Comment by ML-Gaming** [comment]
> Would it be alright for me to apply this change to the dev branch rather than the main branch? I was in the process of working on a way for Monika to change underwear already in 'dev' so I would like your work to overwrite it.

Yea sure go ahead do what you want with it.

**Comment by NickWildish** [comment]
I've implemented this functionality into the main directory now.
However, since there has been some additions where the Auto Hair Change submod now interacts with ours to change clothes during sexting, this had to be changed around to get it to work.
Nevertheless, the ability to unlock the pink and black underwear has been added.

Closing as implemented.

**Pull request closed without merging**
