### PR TITLE
Blushing's nsfw_fetishes.rpy

### PR DESCRIPTION
**Pull request by TheBlushingSoldier**
Made topic about having fetishes

### CODE REVIEW

**Comment by NickWildish** [comment]
We already have a topic regarding fetishes. You can check it out [here](https://github.com/NickWildish/Mas-NSFW-Submod/blob/main/game/Submods/NSFW%20Submod/nsfw_topics.rpy) starting at line 213.

I think we can still add this though, so if you could modify the topic slightly and rename it, we can add it in.

**Comment by NickWildish** [comment]
Maybe if it were more related to kink shaming?

**Review by TheBlushingSoldier — COMMENTED** [review]
Changed name.

**Comment by NickWildish** [comment]
Looks good! I'll merge it now.

**Pull request merged**
